# Generated by Django 2.0.2 on 2018-02-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCity',
            fields=[
                ('idcity', models.AutoField(db_column='idCity', primary_key=True, serialize=False)),
                ('namecity', models.CharField(blank=True, db_column='nameCity', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_city',
            },
        ),
        migrations.CreateModel(
            name='TbCountry',
            fields=[
                ('idcountry', models.AutoField(db_column='idCountry', primary_key=True, serialize=False)),
                ('namecountry', models.CharField(blank=True, db_column='nameCountry', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_country',
            },
        ),
        migrations.CreateModel(
            name='TbStatus',
            fields=[
                ('idstatus', models.AutoField(db_column='idStatus', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tb_status',
            },
        ),
        migrations.CreateModel(
            name='TbStore',
            fields=[
                ('idstore', models.AutoField(db_column='idStore', primary_key=True, serialize=False)),
                ('namestore', models.CharField(blank=True, db_column='nameStore', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phonestore', models.CharField(blank=True, db_column='phoneStore', max_length=200, null=True)),
                ('mailstore', models.CharField(blank=True, db_column='mailStore', max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lon', models.CharField(blank=True, max_length=200, null=True)),
                ('dateregister', models.DateTimeField(blank=True, db_column='dateRegister', null=True)),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbCity')),
                ('idstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStatus')),
            ],
            options={
                'db_table': 'tb_store',
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='userName', max_length=200, null=True, unique=True)),
                ('mailuser', models.CharField(blank=True, db_column='mailUser', max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=200, null=True)),
                ('dni', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('dateofbirth', models.DateTimeField(blank=True, db_column='dateOfBirth', null=True)),
                ('phoneuser', models.CharField(blank=True, db_column='phoneUser', max_length=200, null=True)),
                ('passuser', models.CharField(blank=True, db_column='passUser', max_length=255, null=True)),
                ('idstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStatus')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='TbUserStore',
            fields=[
                ('iduserstore', models.AutoField(db_column='idUserStore', primary_key=True, serialize=False)),
                ('idstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStatus')),
                ('idstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStore')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbUser')),
            ],
            options={
                'db_table': 'tb_user_store',
            },
        ),
        migrations.AddField(
            model_name='tbcountry',
            name='idstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStatus'),
        ),
        migrations.AddField(
            model_name='tbcity',
            name='idcountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbCountry'),
        ),
        migrations.AddField(
            model_name='tbcity',
            name='idstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.TbStatus'),
        ),
    ]
